// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Saloon;

#nullable disable

namespace Saloon.Migrations
{
    [DbContext(typeof(SaloonDbContext))]
    partial class SaloonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Saloon.Booking", b =>
                {
                    b.Property<string>("BookingID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BookingID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Saloon.Customer", b =>
                {
                    b.Property<string>("NIC")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NIC");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Saloon.Service", b =>
                {
                    b.Property<string>("ServiceID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ServiceID");

                    b.ToTable("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
